### ISSUE TITLE
Changing chain lengths on user side causes sampling to hang

### ISSUE THREAD

**Issue by jmsull** [HerculesJack/bayesfast#1]
When I trying to shorten the chain in the first sample step like this:

sam_0 = bf.recipe.SampleStep(s_1, alpha_n=2, reuse_steps=1, 
                                                     fit_options={'use_mu_f': True},
                                                      sample_options={"sampler_options":{
                                                                                               "n_iter":1000,
                                                                                               "n_warmup":250
                                                                                              }})

bayesfast just hangs after completing the optimize step. A similar thing happens for the sampling that occurs in the optimize step when you try to change n_iter, n_warmup through "hmc_options"

I traced the issue to here:
https://github.com/HerculesJack/bayesfast/blob/52e9f405e6c80232ab523165e54406449ac4d0e1/bayesfast/core/recipe.py#L649
where it seems like for the surrogate model, a dictionary that has two separate elements (both dictionaries called "sampler_options" are being passed to the sampler at the same time. I don't know exactly why this would cause it to hang but it does.

I can get the result I want (shortened chains) by directly editing bayesfast here (https://github.com/HerculesJack/bayesfast/blob/52e9f405e6c80232ab523165e54406449ac4d0e1/bayesfast/core/recipe.py#L654), here (https://github.com/HerculesJack/bayesfast/blob/52e9f405e6c80232ab523165e54406449ac4d0e1/bayesfast/core/sample.py#L45), and here (https://github.com/HerculesJack/bayesfast/blob/52e9f405e6c80232ab523165e54406449ac4d0e1/bayesfast/core/sample.py#L53)

**Comment by jmsull** [comment]
And nope I was nesting the dictionaries wrong (was trying to specify n_iter inside of inner sample_options dictionary) - still not sure why it hangs but seems to be working now - sorry for the confusion!

**Comment by HerculesJack** [comment]
1. Yes I realized that nesting the dict options is probably not a good idea, so I'm rewriting this part of interface and may finish it soon.
2. The reason why it hangs is probably due to dask. It should be able to retrieve remote errors to local, but I also found that this is not always true in practice. Will look into this issue at some point. For now, you can see the log of remote workers in the dask server page (you can find the link below the cell where you initialize the dask client).
