### ISSUE TITLE
can't install correctly

### ISSUE THREAD

**Issue by yiyezhilan** [HerculesJack/bayesfast#35]
I installed the package from your command on Windows 10:
    git clone https://github.com/HerculesJack/bayesfast
    cd bayesfast
    pip install -e .
but I got the error:
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///C:/Users/10654/bayesfast
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cython in c:\users\10654\anaconda3\lib\site-packages (from bayesfast==0.1.0.dev2+7796b7c) (0.29.21)
Requirement already satisfied: numpy>=1.17 in c:\users\10654\anaconda3\lib\site-packages (from bayesfast==0.1.0.dev2+7796b7c) (1.19.2)
Collecting multiprocess
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6b/d1/43fd2b01aebd1294777051dadc87b6326dccc1b89f82981f261eaa92d0e8/multiprocess-0.70.11.1-py38-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 1.7 MB/s
Requirement already satisfied: scipy in c:\users\10654\anaconda3\lib\site-packages (from bayesfast==0.1.0.dev2+7796b7c) (1.5.2)
Requirement already satisfied: numdifftools in c:\users\10654\anaconda3\lib\site-packages (from bayesfast==0.1.0.dev2+7796b7c) (0.9.39)
Requirement already satisfied: scikit-learn in c:\users\10654\anaconda3\lib\site-packages (from bayesfast==0.1.0.dev2+7796b7c) (0.23.2)
Requirement already satisfied: matplotlib in c:\users\10654\anaconda3\lib\site-packages (from bayesfast==0.1.0.dev2+7796b7c) (3.3.2)
Requirement already satisfied: threadpoolctl in c:\users\10654\anaconda3\lib\site-packages (from bayesfast==0.1.0.dev2+7796b7c) (2.1.0)
Requirement already satisfied: extension-helpers in c:\users\10654\anaconda3\lib\site-packages (from bayesfast==0.1.0.dev2+7796b7c) (0.1)
Requirement already satisfied: dill>=0.3.3 in c:\users\10654\anaconda3\lib\site-packages (from multiprocess->bayesfast==0.1.0.dev2+7796b7c) (0.3.3)
Requirement already satisfied: joblib>=0.11 in c:\users\10654\anaconda3\lib\site-packages (from scikit-learn->bayesfast==0.1.0.dev2+7796b7c) (0.17.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\10654\anaconda3\lib\site-packages (from matplotlib->bayesfast==0.1.0.dev2+7796b7c) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\10654\anaconda3\lib\site-packages (from matplotlib->bayesfast==0.1.0.dev2+7796b7c) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\10654\anaconda3\lib\site-packages (from matplotlib->bayesfast==0.1.0.dev2+7796b7c) (1.3.0)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\10654\anaconda3\lib\site-packages (from matplotlib->bayesfast==0.1.0.dev2+7796b7c) (2020.6.20)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\10654\anaconda3\lib\site-packages (from matplotlib->bayesfast==0.1.0.dev2+7796b7c) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in c:\users\10654\anaconda3\lib\site-packages (from matplotlib->bayesfast==0.1.0.dev2+7796b7c) (8.0.1)
Requirement already satisfied: six>=1.5 in c:\users\10654\appdata\roaming\python\python38\site-packages (from python-dateutil>=2.1->matplotlib->bayesfast==0.1.0.dev2+7796b7c) (1.15.0)
Installing collected packages: multiprocess, bayesfast
  Running setup.py develop for bayesfast
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\10654\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\10654\\bayesfast\\setup.py'"'"'; __file__='"'"'C:\\Users\\10654\\bayesfast\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\10654\bayesfast\
    Complete output (50 lines):
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IE:\Windows Kits\10\include\10.0.19041.0\ucrt" "-IE:\Windows Kits\10\include\10.0.19041.0\shared" "-IE:\Windows Kits\10\include\10.0.19041.0\um" "-IE:\Windows Kits\10\include\10.0.19041.0\winrt" "-IE:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tctest_openmp.c /Foobjects\test_openmp.obj -openmp
    test_openmp.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\um\x64" objects\test_openmp.obj /OUT:test_openmp.exe
    正在生成代码
    已完成代码的生成
    Compiling Cython/C/C++ extension with OpenMP support
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IE:\Windows Kits\10\include\10.0.19041.0\ucrt" "-IE:\Windows Kits\10\include\10.0.19041.0\shared" "-IE:\Windows Kits\10\include\10.0.19041.0\um" "-IE:\Windows Kits\10\include\10.0.19041.0\winrt" "-IE:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tctest_openmp.c /Foobjects\test_openmp.obj -openmp
    test_openmp.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\um\x64" objects\test_openmp.obj /OUT:test_openmp.exe
    正在生成代码
    已完成代码的生成
    Compiling Cython/C/C++ extension with OpenMP support
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IE:\Windows Kits\10\include\10.0.19041.0\ucrt" "-IE:\Windows Kits\10\include\10.0.19041.0\shared" "-IE:\Windows Kits\10\include\10.0.19041.0\um" "-IE:\Windows Kits\10\include\10.0.19041.0\winrt" "-IE:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tctest_openmp.c /Foobjects\test_openmp.obj -openmp
    test_openmp.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\um\x64" objects\test_openmp.obj /OUT:test_openmp.exe
    正在生成代码
    已完成代码的生成
    Compiling Cython/C/C++ extension with OpenMP support
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IE:\Windows Kits\10\include\10.0.19041.0\ucrt" "-IE:\Windows Kits\10\include\10.0.19041.0\shared" "-IE:\Windows Kits\10\include\10.0.19041.0\um" "-IE:\Windows Kits\10\include\10.0.19041.0\winrt" "-IE:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tctest_openmp.c /Foobjects\test_openmp.obj -openmp
    test_openmp.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\um\x64" objects\test_openmp.obj /OUT:test_openmp.exe
    正在生成代码
    已完成代码的生成
    Compiling Cython/C/C++ extension with OpenMP support
    running develop
    running egg_info
    writing bayesfast.egg-info\PKG-INFO
    writing dependency_links to bayesfast.egg-info\dependency_links.txt
    writing requirements to bayesfast.egg-info\requires.txt
    writing top-level names to bayesfast.egg-info\top_level.txt
    adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
    reading manifest file 'bayesfast.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'bayesfast.egg-info\SOURCES.txt'
    running build_ext
    building 'bayesfast.transforms._constraint' extension
    creating build
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\bayesfast
    creating build\temp.win-amd64-3.8\Release\bayesfast\transforms
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\10654\AppData\Local\Temp\pip-build-env-lp306cxm\overlay\Lib\site-packages\numpy\core\include -IC:\Users\10654\anaconda3\include -IC:\Users\10654\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IE:\Windows Kits\10\include\10.0.19041.0\ucrt" "-IE:\Windows Kits\10\include\10.0.19041.0\shared" "-IE:\Windows Kits\10\include\10.0.19041.0\um" "-IE:\Windows Kits\10\include\10.0.19041.0\winrt" "-IE:\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcbayesfast/transforms/_constraint.c /Fobuild\temp.win-amd64-3.8\Release\bayesfast/transforms/_constraint.obj -openmp
    _constraint.c
    C:\Users\10654\AppData\Local\Temp\pip-build-env-lp306cxm\overlay\Lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    creating C:\Users\10654\bayesfast\build\lib.win-amd64-3.8
    creating C:\Users\10654\bayesfast\build\lib.win-amd64-3.8\bayesfast
    creating C:\Users\10654\bayesfast\build\lib.win-amd64-3.8\bayesfast\transforms
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\10654\anaconda3\libs /LIBPATH:C:\Users\10654\anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:E:\Windows Kits\10\lib\10.0.19041.0\um\x64" m.lib /EXPORT:PyInit__constraint build\temp.win-amd64-3.8\Release\bayesfast/transforms/_constraint.obj /OUT:build\lib.win-amd64-3.8\bayesfast\transforms\_constraint.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\bayesfast/transforms\_constraint.cp38-win_amd64.lib
    LINK : fatal error LNK1181: 无法打开输入文件“m.lib”
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\10654\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\10654\\bayesfast\\setup.py'"'"'; __file__='"'"'C:\\Users\\10654\\bayesfast\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by HerculesJack** [comment]
The issue is that the [Unix dynamic linking of libc math library](https://cython.readthedocs.io/en/latest/src/tutorial/external.html#dynamic-linking) does not work on Windows. You'd need to figure out what the correct way for this on Windows is. I'm not familiar with Cython on Windows though. I guess a first try might be to just remove all those `libraries=["m"]` in `setup.py`.

We haven't added Windows support for bayesfast yet. So if you want to use it on Windows, I'd recommend trying [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

Hope this helps!

**Comment by yiyezhilan** [comment]
Thanks a lot!!! I will try that!
